# Generated by Django 5.0.3 on 2024-03-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0002_alter_user_date_of_birth_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Чоловік', 'Чоловік'), ('Жінка', 'Жінка')], default='Чоловік', max_length=8),
        ),
    ]
